FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# grigolato-lugio-se2

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/questions]

### List All Questions [PUT]





### List All Questions [GET]

+ Response 200 (application/json)

        [
            
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

{
  "allOf": [
    {
      "required": [
        "id",
        "name",
        "is_still_in"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "is_still_in": {
          "type": "boolean"
        }
        
        
        },
   
    }
    ]
}